language: cpp
dist: focal
os: linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-$(lsb_release -cs)-12
    packages:
      - g++-12
      - clang-12
      - libcppunit-dev
      - libnetcdf-dev

before_install:
  - if [[ "$CXX" == "g++" ]]; then export CXX=g++-12 CC=gcc-12; fi
  - if [[ "$CXX" == "clang++" ]]; then export CXX=clang++-12 CC=clang-12; fi

before_script:
  - wget https://downloads.unidata.ucar.edu/netcdf-c/4.9.2/netcdf-c-4.9.2.tar.gz
  - tar xf netcdf-cxx4-9.2.tar.gz
  - pushd netcdf-cxx4-9.2
  - CXXFLAGS=$NETCDF_CXX4_CXXFLAGS ./configure --prefix=/usr/local
  - make
  - sudo make install
  - popd

script:
  - cd tst/unittests
  - mkdir build && cd build
  - cmake ..
  - make
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - ./unittests

notifications:
  email: false

cache:
  directories:
    - $HOME/.cache

