name: CI/CD

on:
  push:
    branches:
      - master
      - v0.1.0-alpha
  pull_request:
    branches:
      - master
      - v0.1.0-alpha

jobs:
  build-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Cache CUDA Docker Image
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-cuda-docker-${{ hashFiles('cuda-docker-image-cache-key.txt') }}
          restore-keys: |
            ${{ runner.os }}-cuda-docker-
      - name: Pull Docker Image
        run: docker pull nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

      - name: Build CUDA Target
        run: docker build . --target build

  test-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Cache Google Test Framework
        id: cache-gtest
        uses: actions/cache@v2
        with:
          path: /github/workspace
          key: ${{ runner.os }}-gtest-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-gtest-
      
      - name: Install Google Test Framework
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends cmake
          if [ -z "${{ steps.cache-gtest.outputs.cache-hit }}" ]; then
            git clone https://github.com/google/googletest.git ./googletest
            cd ./googletest
            cmake .
            make
            sudo make install
          else
            echo "Google Test Framework is already cached."
          fi
